Add support for initializing from strings that are frozen
jfairbank/chroma pull request #24
Opened 2017-04-25 05:06 UTC by okoriko

As the current implementation was mutating the string, the following would raise an error:
```
'red'.freeze.paint
```

2017-04-26 00:55 UTC, jfairbank requested changes

2017-04-26 00:55 UTC, jfairbank commented on lib/chroma/rgb_generator.rb
> +# frozen_string_literal: true
Nitpicky, but I don't think we need the frozen string comment here.

2017-04-26 00:56 UTC, jfairbank commented
Hi, @okoriko!

Thanks for the PR. This is a good fix for newer versions of Ruby. Do you mind adding a test case as well as updating the travis rvm versions as a sanity check? Thanks!

2017-04-26 01:12 UTC, okoriko commented on lib/chroma/rgb_generator.rb
> +# frozen_string_literal: true
Sorry, that one came automatically from my setup. I'll remove it :+1:

2021-09-13 20:10 UTC, evanleck commented
@okoriko FYI I've created a fork/rename of Chroma that I intend to maintain and I've added this change there https://github.com/evanleck/kodachroma

2022-07-29 04:04 UTC, closed without merging